server:
  port: 8080
spring:
  application:
    name: Future Management
  datasource:
    url: jdbc:postgresql://${db_host:localhost}:5432/future_management
    username: ${db_user:postgres}
    password: ${db_password:Pavan@2001}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

pagination:
  default-size: 10
  default-page: 0
  default-shortOrder: desc
  default-featureShorting: id

logging:
  level:
    com:
      fasterxml:
        jackson: DEBUG