server:
  port: 8080
spring:
  application:
    name: Future Management
  datasource:
    url: jdbc:postgresql://${db_host:192.168.0.118}:5432/future_management
    username: ${db_user:postgres}
    password: ${db_password:Pavan@2001}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

pagination:
  default-size: 10
  default-page: 0
  default-shortOrder: desc
  default-featureShorting: id

logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.hibernate.type.descriptor.converter: DEBUG
    org.hibernate.SQL: DEBUG

feature:
  strategies:
    - name: BooleanFeatureStrategy
      description: This strategy is used to work based on boolean values true or false.
    - name: JWTClaimFeatureStrategy
      description: This strategy is used to work based on JWT claim key and value.
    - name: HTTPRequestFeatureStrategy
      description: This strategy is used to work based on HTTP request. That could be a URL path, header or request body.
    - name: ScheduleFeatureStrategy
      description: This strategy is used to enable or disable the feature based on dynamic conditions.