databaseChangeLog:
  - changeSet:
      id: env-1
      author: pavan
      changes:
        - createTable:
            tableName: environment
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: description
                  type: VARCHAR(255)
              - column:
                  name: created_at
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: modified_at
                  type: TIMESTAMP
                  constraints:
                    nullable: false

        - createTable:
            tableName: environment_owners
            columns:
              - column:
                  name: environment_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: owner
                  type: VARCHAR(255)
                  constraints:
                    nullable: false

        - addForeignKeyConstraint:
            baseTableName: environment_owners
            baseColumnNames: environment_id
            referencedTableName: environment
            referencedColumnNames: id
            constraintName: fk_environment_owners_environment
            onDelete: CASCADE

        - addPrimaryKey:
            tableName: environment_owners
            columnNames: environment_id, owner
            constraintName: pk_environment_owners